spring.application.name=visu-gastos

spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB:visu_gastos}
spring.datasource.username=${POSTGRES_USER:visu}
spring.datasource.password=${POSTGRES_PASSWORD:visu}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true